services:
  web:
    build: .
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - migration
    env_file: ./.env
  migration:
    build: .
    links:
      - db
    env_file: ./.env
    command: ['yarn', 'prisma', 'migrate', 'deploy', '--preview-feature']
  db:
    image: postgres:13
    env_file: ./db.env
    volumes:
      - zws-postgres-storage:/var/lib/postgresql/data
    expose:
      - '5432'
volumes:
  zws-postgres-storage:
    external: true
